FROM rust:1.84 AS builder

WORKDIR /app
RUN apt update && apt install lld clang -y
COPY . .
ENV SQLX_OFFLINE=true
RUN cargo build --release

FROM debian:bookworm-slim AS runtime
WORKDIR /app
RUN apt-get update -y
COPY --from=builder /app/target/release/feeder feeder
ENTRYPOINT ["./feeder"]
