version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      "COLLECTOR_ZIPKIN_HOST_PORT": "9411"
      "COLLECTOR_OTLP_ENABLED": "true"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      "POSTGRES_USER": "patient"
      "POSTGRES_PASSWORD": "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
  migrator:
    image: migrator
    build:
      context: .
      dockerfile: Dockerfile.Migrator
    environment:
      "DATABASE_URL": "postgres://patient:password@postgres:5432/patient"
    depends_on:
      postgres:
        condition: service_healthy
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile.API
    ports:
      - "8080:8080"
    environment:
      "APP_TRACING_ADDRESS": "http://jaeger:4317"
    depends_on:
      jaeger:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
  feeder:
    image: feeder
    build:
      context: .
      dockerfile: Dockerfile.Feeder
    environment:
      "APP_API_ADDRESS": "http:/api:8080"
    depends_on:
      api:
        condition: service_started
